name: Deploy Website

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: deploy website
        run: |
          echo "start upload to s3"
          aws s3 cp index.html s3://nice-place-paca-bucket-213421/ --acl public-read
